// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: ebpfence.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EBPFence_ListBlockedPIDs_FullMethodName = "/ebpfence.EBPFence/ListBlockedPIDs"
	EBPFence_UnblockPID_FullMethodName      = "/ebpfence.EBPFence/UnblockPID"
)

// EBPFenceClient is the client API for EBPFence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EBPFenceClient interface {
	ListBlockedPIDs(ctx context.Context, in *ListBlockedPIDsRequest, opts ...grpc.CallOption) (*ListBlockedPIDsResponse, error)
	UnblockPID(ctx context.Context, in *UnblockPIDRequest, opts ...grpc.CallOption) (*UnblockPIDResponse, error)
}

type eBPFenceClient struct {
	cc grpc.ClientConnInterface
}

func NewEBPFenceClient(cc grpc.ClientConnInterface) EBPFenceClient {
	return &eBPFenceClient{cc}
}

func (c *eBPFenceClient) ListBlockedPIDs(ctx context.Context, in *ListBlockedPIDsRequest, opts ...grpc.CallOption) (*ListBlockedPIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlockedPIDsResponse)
	err := c.cc.Invoke(ctx, EBPFence_ListBlockedPIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eBPFenceClient) UnblockPID(ctx context.Context, in *UnblockPIDRequest, opts ...grpc.CallOption) (*UnblockPIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnblockPIDResponse)
	err := c.cc.Invoke(ctx, EBPFence_UnblockPID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EBPFenceServer is the server API for EBPFence service.
// All implementations must embed UnimplementedEBPFenceServer
// for forward compatibility.
type EBPFenceServer interface {
	ListBlockedPIDs(context.Context, *ListBlockedPIDsRequest) (*ListBlockedPIDsResponse, error)
	UnblockPID(context.Context, *UnblockPIDRequest) (*UnblockPIDResponse, error)
	mustEmbedUnimplementedEBPFenceServer()
}

// UnimplementedEBPFenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEBPFenceServer struct{}

func (UnimplementedEBPFenceServer) ListBlockedPIDs(context.Context, *ListBlockedPIDsRequest) (*ListBlockedPIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlockedPIDs not implemented")
}
func (UnimplementedEBPFenceServer) UnblockPID(context.Context, *UnblockPIDRequest) (*UnblockPIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnblockPID not implemented")
}
func (UnimplementedEBPFenceServer) mustEmbedUnimplementedEBPFenceServer() {}
func (UnimplementedEBPFenceServer) testEmbeddedByValue()                  {}

// UnsafeEBPFenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EBPFenceServer will
// result in compilation errors.
type UnsafeEBPFenceServer interface {
	mustEmbedUnimplementedEBPFenceServer()
}

func RegisterEBPFenceServer(s grpc.ServiceRegistrar, srv EBPFenceServer) {
	// If the following call panics, it indicates UnimplementedEBPFenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EBPFence_ServiceDesc, srv)
}

func _EBPFence_ListBlockedPIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockedPIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFenceServer).ListBlockedPIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFence_ListBlockedPIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFenceServer).ListBlockedPIDs(ctx, req.(*ListBlockedPIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EBPFence_UnblockPID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnblockPIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EBPFenceServer).UnblockPID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EBPFence_UnblockPID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EBPFenceServer).UnblockPID(ctx, req.(*UnblockPIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EBPFence_ServiceDesc is the grpc.ServiceDesc for EBPFence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EBPFence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ebpfence.EBPFence",
	HandlerType: (*EBPFenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBlockedPIDs",
			Handler:    _EBPFence_ListBlockedPIDs_Handler,
		},
		{
			MethodName: "UnblockPID",
			Handler:    _EBPFence_UnblockPID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ebpfence.proto",
}
