use anyhow::Context;
use std::collections::VecDeque;
use std::mem::MaybeUninit;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
#[cfg(test)]
use std::sync::Condvar;
use std::time::Duration;

// Must match the BPF C struct event_t (see bpf/deny_new_reads.bpf.c)
#[repr(C)]
#[derive(Debug, Clone)]
pub struct Event {
    pub pid: u32,
    pub uid: u32,
    pub comm: [u8; 16],
    pub filename: [u8; 256],
    pub flags: i32,
}

pub trait EBPFProvider: Send + Sync {
    fn read_event(&self) -> anyhow::Result<Event>;
    fn block_pid(&self, pid: u32) -> anyhow::Result<()>;
    fn unblock_pid(&self, pid: u32) -> anyhow::Result<()>;
    fn close(&self);
}

// ---------------------------------------------------------------------------
// Real eBPF provider (requires kernel 5.7+ with LSM BPF enabled at boot)
// ---------------------------------------------------------------------------

// Include the skeleton generated by build.rs via libbpf-cargo.
mod bpf {
    include!(concat!(env!("OUT_DIR"), "/deny_new_reads.skel.rs"));
}
use bpf::*;

use crate::config::BlockStrategy;
use libbpf_rs::skel::{OpenSkel, SkelBuilder};
use libbpf_rs::{MapCore, MapFlags, RingBufferBuilder};

fn check_lsm_bpf_enabled() -> anyhow::Result<()> {
    let data = std::fs::read_to_string("/sys/kernel/security/lsm")
        .context("cannot read /sys/kernel/security/lsm")?;
    if data.split(',').any(|m| m.trim() == "bpf") {
        return Ok(());
    }
    anyhow::bail!(
        "LSM BPF is not enabled (current LSM list: {:?}); reboot with lsm=...,bpf kernel parameter",
        data.trim()
    )
}

fn parse_event(data: &[u8]) -> Option<Event> {
    if data.len() < std::mem::size_of::<Event>() {
        return None;
    }
    // Safety: Event is #[repr(C)] with only integer and array fields.
    // data comes from the BPF ring buffer and was written with the matching C struct.
    Some(unsafe { std::ptr::read_unaligned(data.as_ptr() as *const Event) })
}

pub struct RealEBPFProvider {
    // DenyNewReadsSkel<'static>: 'static because the open_obj storage was Box::leaked.
    // The ring buffer is also 'static because its callbacks capture 'static data.
    // Safety invariant: skel and rb are accessed sequentially, never concurrently.
    skel: DenyNewReadsSkel<'static>,
    rb: libbpf_rs::RingBuffer<'static>,
    event_queue: std::sync::Arc<Mutex<VecDeque<Event>>>,
    _links: Vec<libbpf_rs::Link>,
    closed: AtomicBool,
}

// Safety: BPF file descriptors and heap-allocated libbpf objects are safe to
// transfer and share across threads. All access within EventHandler is sequential:
// read_event() runs in spawn_blocking, and block/unblock run after it returns.
unsafe impl Send for RealEBPFProvider {}
unsafe impl Sync for RealEBPFProvider {}

impl RealEBPFProvider {
    pub fn new(strategy: &BlockStrategy) -> anyhow::Result<Self> {
        check_lsm_bpf_enabled()?;

        // Box::leak gives us a '&'static mut MaybeUninit<OpenObject>' so that the
        // skeleton (which borrows it) can be '&'static and therefore moved freely.
        // load() reuses this storage for the Object, so only one leak is needed.
        // The Object value is dropped by OwnedRef when the skel is dropped; the
        // storage itself remains leaked (one small allocation for the daemon lifetime).
        let open_obj: &'static mut MaybeUninit<libbpf_rs::OpenObject> =
            Box::leak(Box::new(MaybeUninit::uninit()));

        let open_skel = DenyNewReadsSkelBuilder::default()
            .open(open_obj)
            .context("open BPF object")?;
        let skel = open_skel.load().context("load BPF programs")?;

        // Attach LSM hooks according to the configured blocking strategy.
        let mut links: Vec<libbpf_rs::Link> = Vec::new();

        if matches!(strategy, BlockStrategy::BlockFiles | BlockStrategy::BlockBoth) {
            let link = skel
                .progs
                .deny_file_open
                .attach_lsm()
                .context("attach file_open LSM hook")?;
            links.push(link);
        }

        if matches!(strategy, BlockStrategy::BlockNetwork | BlockStrategy::BlockBoth) {
            let link = skel
                .progs
                .deny_socket_connect
                .attach_lsm()
                .context("attach socket_connect LSM hook")?;
            links.push(link);
        }

        // Build the ring buffer. The callback (returning i32) pushes events into
        // the shared queue. The BorrowedFd from the map is only held for the duration
        // of build(), so RingBuffer<'static> holds no borrow on skel after construction.
        let event_queue = std::sync::Arc::new(Mutex::new(VecDeque::<Event>::new()));
        let q = event_queue.clone();
        let mut rb_builder = RingBufferBuilder::new();
        rb_builder
            .add(&skel.maps.events as &dyn MapCore, move |data: &[u8]| -> i32 {
                if let Some(event) = parse_event(data) {
                    q.lock().unwrap().push_back(event);
                }
                0
            })
            .context("ring buffer add")?;
        let rb = rb_builder.build().context("ring buffer build")?;

        Ok(RealEBPFProvider {
            skel,
            rb,
            event_queue,
            _links: links,
            closed: AtomicBool::new(false),
        })
    }
}

impl EBPFProvider for RealEBPFProvider {
    fn read_event(&self) -> anyhow::Result<Event> {
        loop {
            if self.closed.load(Ordering::SeqCst) {
                anyhow::bail!("provider closed");
            }
            {
                let mut q = self.event_queue.lock().unwrap();
                if let Some(event) = q.pop_front() {
                    return Ok(event);
                }
            }
            // Poll with a short timeout so close() is noticed promptly.
            self.rb
                .poll(Duration::from_millis(100))
                .map_err(|e| anyhow::anyhow!("ring buffer poll: {}", e))?;
        }
    }

    fn block_pid(&self, pid: u32) -> anyhow::Result<()> {
        let key = pid.to_ne_bytes();
        let val: [u8; 1] = [1];
        self.skel
            .maps
            .blocked_pids
            .update(&key, &val, MapFlags::empty())
            .map_err(|e| anyhow::anyhow!("update blocked_pids: {}", e))
    }

    fn unblock_pid(&self, pid: u32) -> anyhow::Result<()> {
        let key = pid.to_ne_bytes();
        self.skel
            .maps
            .blocked_pids
            .delete(&key)
            .map_err(|e| anyhow::anyhow!("delete from blocked_pids: {}", e))
    }

    fn close(&self) {
        self.closed.store(true, Ordering::SeqCst);
    }
}

// ---------------------------------------------------------------------------
// Mock provider for unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
pub struct MockEBPFProvider {
    events: Mutex<VecDeque<Event>>,
    blocked_pids: Mutex<std::collections::HashSet<u32>>,
    closed: AtomicBool,
    // Notified when close() is called so read_event() can unblock.
    close_cvar: Condvar,
    close_flag: Mutex<bool>,
    // True once the event queue is first found empty (all events consumed).
    pub drained: AtomicBool,
}

#[cfg(test)]
impl MockEBPFProvider {
    pub fn new(events: Vec<Event>) -> Self {
        MockEBPFProvider {
            events: Mutex::new(events.into()),
            blocked_pids: Mutex::new(std::collections::HashSet::new()),
            closed: AtomicBool::new(false),
            close_cvar: Condvar::new(),
            close_flag: Mutex::new(false),
            drained: AtomicBool::new(false),
        }
    }

    pub fn is_pid_blocked(&self, pid: u32) -> bool {
        self.blocked_pids.lock().unwrap().contains(&pid)
    }

    /// Directly signal close to unblock any blocked read_event() call.
    /// Avoids needing to import the EBPFProvider trait in test code.
    pub fn shutdown(&self) {
        self.closed.store(true, Ordering::SeqCst);
        *self.close_flag.lock().unwrap() = true;
        self.close_cvar.notify_all();
    }

    pub fn make_event(pid: u32, uid: u32, comm: &str, filename: &str) -> Event {
        let mut event = Event {
            pid,
            uid,
            comm: [0u8; 16],
            filename: [0u8; 256],
            flags: 0,
        };
        let b = comm.as_bytes();
        event.comm[..b.len().min(15)].copy_from_slice(&b[..b.len().min(15)]);
        let b = filename.as_bytes();
        event.filename[..b.len().min(255)].copy_from_slice(&b[..b.len().min(255)]);
        event
    }
}

#[cfg(test)]
impl EBPFProvider for MockEBPFProvider {
    fn read_event(&self) -> anyhow::Result<Event> {
        loop {
            {
                let mut q = self.events.lock().unwrap();
                if let Some(event) = q.pop_front() {
                    // Don't signal drained here: the event hasn't been processed yet.
                    return Ok(event);
                }
                // Queue is empty AND we're about to block — all events have been
                // returned AND processed by this point.
                self.drained.store(true, Ordering::SeqCst);
            }
            // Block until close() is called.
            let mut flag = self.close_flag.lock().unwrap();
            while !*flag {
                flag = self.close_cvar.wait(flag).unwrap();
            }
            return Err(anyhow::anyhow!("provider closed"));
        }
    }

    fn block_pid(&self, pid: u32) -> anyhow::Result<()> {
        self.blocked_pids.lock().unwrap().insert(pid);
        Ok(())
    }

    fn unblock_pid(&self, pid: u32) -> anyhow::Result<()> {
        self.blocked_pids.lock().unwrap().remove(&pid);
        Ok(())
    }

    fn close(&self) {
        self.closed.store(true, Ordering::SeqCst);
        *self.close_flag.lock().unwrap() = true;
        self.close_cvar.notify_all();
    }
}
